### ISSUE TITLE
error while decoding MB 4 6, bytestream -9

### ISSUE THREAD

**Issue by baharna2** [ahmetozlu/vehicle_counting_tensorflow#17]
Hi,
Thank you so much for providing this repo.
I'm running your code in a virtual machine which I only have access to the terminal, so I decided to save each frame instead of displaying it. I get this error when running the code
error while decoding MB 4 6, bytestream -9
The code stops after processing first frame of video file. I'd be thankful if you kindly help on that.

Thanks,

Bahareh

**Comment by ahmetozlu** [comment]
Could you share some more details about the error?

I am also planning to add new feature that are about  saving counting result as an output video.

By the way, if you think that this repo is useful, please give a star.. It is important to support open source community. Please be aware of that fact!

**Comment by baharna2** [comment]
Thank you for your reply.

I'll give a start for sure, after I could successfully test the projects.

I googled the error, it seems that the error has something to do with ffmpeg  that is required to handle the video file and this needs to linked to opencv at the time of installation. Here is a link to that.

https://github.com/vdkkia/Using-Opencv-with-ffmpeg-in-python3-

Moreover, there are some inconsistent indentations for tabs and spaces that arises while running. There are also some errors when importing several modules which you kindly provided. I needed to add those paths to the system at the beginning of three of the scripts.


Additionally, the module you provided for the direction does not seem to be general. It can be applied to very specific scenes. I wonder if we can talk further on that through the Skype.


Thanks again for providing such a modular work. I was wonder when you expect the work to get finished and if you are adding other major features.

[https://avatars0.githubusercontent.com/u/4618481?s=400&v=4]<https://github.com/vdkkia/Using-Opencv-with-ffmpeg-in-python3->

GitHub - vdkkia/Using-Opencv-with-ffmpeg-in-python3 ...<https://github.com/vdkkia/Using-Opencv-with-ffmpeg-in-python3->
github.com
GitHub is where people build software. More than 28 million people use GitHub to discover, fork, and contribute to over 85 million projects.




________________________________

**Comment by baharna2** [comment]
Hi,
Yes, I’m using python 3.x . That’s why all those indentation and packaging issue happens. I fixed them all by the way.
However there is a more serious problem. It doesn’t detect any of the vehicles in the video, even when I changed the utilized model to faster rcnn, mask rcnn etc, however I tried to save the result for one of the video frame using object detection API github only (not your project code) through ssd mobilenet and it’s able to partially detect the card. There should be something wrong with either vehicle-detection-main or visualization_utils script. Do you have any idea. There is no error, but no car is detected when using your code.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by ahmetozlu** [comment]
The project has been updated from python2 to python3 and all the indentation problem fixed.

"However there is a more serious problem. It doesn’t detect any of the vehicles in the video, even when I changed the utilized model to faster rcnn, mask rcnn etc, however I tried to save the result for one of the video frame using object detection API github only (not your project code) through ssd mobilenet and it’s able to partially detect the card. There should be something wrong with either vehicle-detection-main or visualization_utils script. Do you have any idea. There is no error, but no car is detected when using your code." -> Could you prove it by any screen shots or any videos? It looks not possible that [TenworFlow Object Detection API](https://github.com/tensorflow/models/tree/master/research/object_detection) can detect the some objects that my project can not detects because my project has been built on top of [TensorFlow Object Counting API](https://github.com/ahmetozlu/tensorflow_object_counting_api) that has been built on top of [TensorFlow Object Detection API](https://github.com/tensorflow/models/tree/master/research/object_detection)..
