### ISSUE TITLE
Save the detected video

### ISSUE THREAD

**Issue by redhat12345** [ahmetozlu/vehicle_counting_tensorflow#61]
Hi,
Can you please help me to save the detected video? How can I save the detected video?

Thanks in advanced.

**Comment by ahmetozlu** [comment]
[Instead of showing each frame using imshow function](https://github.com/ahmetozlu/vehicle_counting_tensorflow/blob/master/vehicle_detection_main.py#L228), the processed frames can be saved as an output video using OpenCV. [Here is a tutorial](https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_gui/py_video_display/py_video_display.html#saving-a-video).
